### PR TITLE
fix: Placed downgraded symbols from version script correctly in .symtab

### LINKED ISSUE #1508: Babl fails to link with Wild due to global symbols
Babl's build system (tested version 0.1.118) fails with the error:

<details>

```
[165/277] /usr/bin/python3 /var/tmp/portage/media-libs/babl-0.1.118/work/babl-0.1.118/tools/defcheck.py babl/babl.def
FAILED: [code=255] check-def-files
/usr/bin/python3 /var/tmp/portage/media-libs/babl-0.1.118/work/babl-0.1.118/tools/defcheck.py babl/babl.def

Problem found in babl/babl.def
  the following symbols are in the library,
  but are not listed in the .def-file:
     + add_check_overflow
     + babl_base_destroy_generic
     + babl_base_destroy_x86_64_v2
     + babl_base_init
     + babl_base_init_generic
     + babl_base_init_x86_64_v2
     + babl_base_model_cmyk_generic
     + babl_base_model_cmyk_x86_64_v2
     + babl_base_model_gray_generic
     + babl_base_model_gray_x86_64_v2
     + babl_base_model_rgb_generic
     + babl_base_model_rgb_x86_64_v2
     + babl_base_model_ycbcr_generic
     + babl_base_model_ycbcr_x86_64_v2
     + babl_base_type_float_generic
     + babl_base_type_float_x86_64_v2
     + babl_base_type_half_generic
     + babl_base_type_half_x86_64_v2
     + babl_base_type_u15_generic
     + babl_base_type_u15_x86_64_v2
     + babl_base_type_u16_generic
     + babl_base_type_u16_x86_64_v2
     + babl_base_type_u32_generic
     + babl_base_type_u32_x86_64_v2
     + babl_base_type_u8_generic
     + babl_base_type_u8_x86_64_v2
     + babl_calloc
     + babl_component_class_for_each
     + babl_component_db
     + babl_component_from_id
     + babl_conversion
     + babl_conversion_cost
     + babl_conversion_create_name
     + babl_conversion_db
     + babl_conversion_error
     + babl_conversion_find
     + babl_conversion_from_id
     + babl_core_init
     + babl_cpu_accel_set_use
     + babl_db_count
     + babl_db_exist
     + babl_db_insert
     + babl_die
     + babl_doc
     + babl_dup
     + babl_extension
     + babl_extension_base
     + babl_extension_class_for_each
     + babl_extension_db
     + babl_extension_deinit
     + babl_extension_from_id
     + babl_extension_load_dir_list
     + babl_fish_class_for_each
     + babl_fish_get_id
     + babl_fish_mutex
     + babl_fish_reference
     + babl_fish_reference_process
     + babl_fish_simple
     + babl_format_db
     + babl_format_from_id
     + babl_format_loss
     + babl_format_mutex
     + babl_format_with_model_as_type
     + babl_formats_init_generic
     + babl_formats_init_x86_64_v2
     + babl_get_conversion_test_pixels
     + babl_get_doc
     + babl_get_format_test_pixels
     + babl_get_model_test_pixels
     + babl_get_num_conversion_test_pixels
     + babl_get_num_format_test_pixels
     + babl_get_num_model_test_pixels
     + babl_get_num_path_test_pixels
     + babl_get_num_type_test_pixels
     + babl_get_path_test_pixels
     + babl_get_type_test_pixels
     + babl_hash_by_int
     + babl_hash_by_str
     + babl_hash_table_find
     + babl_hash_table_init
     + babl_hash_table_insert
     + babl_hash_table_size
     + babl_hmpf_on_name_lookups
     + babl_image_from_linear
     + babl_image_new
     + babl_in_fish_path
     + babl_init_db
     + babl_internal_destroy
     + babl_internal_init
     + babl_list_copy
     + babl_list_destroy
     + babl_list_each
     + babl_list_init
     + babl_list_init_with_size
     + babl_list_insert_last
     + babl_list_remove_last
     + babl_model_db
     + babl_model_from_id
     + babl_mutex_destroy
     + babl_mutex_lock
     + babl_mutex_new
     + babl_mutex_unlock
     + babl_realloc
     + babl_reference_mutex
     + babl_rel_avg_error
     + babl_remodel_mutex
     + babl_remodel_with_space
     + babl_sampling_class_for_each
     + babl_sampling_class_init
     + babl_set_destructor
     + babl_set_free
     + babl_set_malloc
     + babl_sizeof
     + babl_space_class_for_each
     + babl_space_class_init
     + babl_space_from_gray_trc
     + babl_space_match_trc_matrix
     + babl_space_mutex
     + babl_store_db
     + babl_strcat
     + babl_strdup
     + babl_test_lut
     + babl_trc_class_for_each_generic
     + babl_trc_class_for_each_x86_64_v2
     + babl_trc_class_init
     + babl_trc_formula_cie
     + babl_trc_formula_srgb
     + babl_trc_lookup_by_name
     + babl_trc_lookup_by_name_generic
     + babl_trc_lookup_by_name_x86_64_v2
     + babl_trc_lut
     + babl_trc_lut_find
     + babl_trc_new_generic
     + babl_trc_new_x86_64_v2
     + babl_type_db
     + babl_type_from_id
     + format_new_from_format_with_space
     + icc_state_new
     + mul_check_overflow
     + write_trc
```

</details

Their build system checks the resulting shared objects to make sure they contain only the allowed symbols.

This is the version script they are using:

<details>

```
V0_1_0 {
    global:
        babl_component;
        babl_component_new;
        babl_conversion_get_destination_space;
        babl_conversion_get_source_space;
        babl_conversion_new;
        babl_chromatic_adaptation_matrix;
        babl_cpu_accel_get_support;
        babl_exit;
        babl_fast_fish;
        babl_fish;
        babl_format;
        babl_format_exists;
        babl_format_get_bytes_per_pixel;
        babl_format_get_model;
        babl_format_get_n_components;
        babl_format_get_space;
        babl_format_get_type;
        babl_format_get_encoding;
        babl_format_has_alpha;
        babl_format_is_format_n;
        babl_format_is_palette;
        babl_format_n;
        babl_format_new;
        babl_format_with_space;
        babl_free;
        babl_get_model_flags;
        babl_get_name;
        babl_get_user_data;
        babl_get_version;
        babl_init;
        babl_introspect;
        babl_malloc;
        babl_model;
        babl_model_is;
        babl_model_with_space;
        babl_model_new;
        babl_new_palette;
        babl_new_palette_with_space;
        babl_palette_reset;
        babl_palette_set_palette;
        babl_process;
        babl_process_rows;
        babl_sampling;
        babl_set_user_data;
        babl_space;
        babl_space_from_rgbxyz_matrix;
        babl_space_from_chromaticities;
        babl_space_from_icc;
        babl_space_get;
        babl_space_get_icc;
        babl_space_get_rgbtoxyz;
        babl_space_get_rgb_luminance;
        babl_space_to_xyz;
        babl_space_from_xyz;
        babl_space_to_icc;
        babl_space_with_trc;
        babl_space_is_cmyk;
        babl_space_is_gray;
        babl_space_is_rgb;
        babl_space_get_gamma;
        babl_icc_make_space;
        babl_icc_get_key;
        babl_ticks;
        babl_type;
        babl_type_new;
        babl_trc;
        babl_trc_gamma;
        babl_trc_new;
        babl_db_exist_by_name;
        babl_db_find;
        babl_db_init;
        babl_db_exist_by_id;
        babl_db_each;
        babl_formats_count;
        babl_format_class_for_each;
        babl_gc;
        babl_model_class_for_each;
        babl_type_class_for_each;
        babl_conversion_class_for_each;
        babl_set_extender;
        babl_extension_quiet_log;
        babl_fish_path;
        babl_fish_get_process;
        babl_extender;
        babl_class_name;
        babl_sanity;
        babl_type_is_symmetric;
        babl_model_is_symmetric;
        babl_fish_db;
        babl_polynomial_approximate_gamma;
        babl_backtrack;
    local:
        *;
};
```

</details>

### PR DESCRIPTION
**Pull request by Blazearth**
## Fix: Place version script downgraded symbols in .symtab local section

Fixes #1508

I have fixed the problem by first making changes in the layout where the space for local symbols is calculated. Made a function to check for both the flags local or downgraded_to_local. Since in the starting only when symbols are loaded from .o files symtab it then only checks it against the version script. In rust version scripts it works by downgrading all symbols to local then it declare global from them so that doesnt causes problem.
Secondly made changes in the elf_writer to check against the flag and change the binding.
This ensures the elf format that all locals comes first before global.

### CODE REVIEW

File: libwild/src/layout.rs [hunk 1]
```diff
@@ -4966,6 +5040,13 @@ impl<'data> ObjectLayoutState<'data> {
     }
 }
 
+/// Returns true if a symbol should be treated as local in the symbol table.
+/// This includes both originally-local symbols and symbols downgraded by version scripts.
+#[inline]
+fn is_symtab_local(sym: &crate::elf::Symbol, flags: ValueFlags) -> bool {
+    sym.is_local() || flags.is_downgraded_to_local()
+}
```
Comment (mati865) [inline libwild/src/layout.rs:5048]: It should be deduplicated with the instance in `elf_writer.rs` file.

Comment (Blazearth) [reply libwild/src/layout.rs:5048]: Yes i missed it, so should i raise a new PR since this is merged or i leave it for now.

Comment (mati865) [reply libwild/src/layout.rs:5048]: Open a new pull request please.
