### PR TITLE
Output dynamic executable when the executable depends on shared objects

### LINKED ISSUE #836: --export-dynamic: thread 'main' panicked at libwild/src/layout.rs:289:14:
@mati865 I noticed the following panic in one of the Mold tests after 0c5cd7e74bdcec6ee815fb5bff3fac8e601dd217:
```
$ cp ~/Programming/wild/ld mold && ../test/export-dynamic.sh
...
+ ./mold -o out/test/x86_64/export-dynamic/exe out/test/x86_64/export-dynamic/a.o out/test/x86_64/export-dynamic/b.so --export-dynamic

thread 'main' panicked at libwild/src/layout.rs:289:14:
Dynamic symbol definitions should start > 0: TryFromIntError(())
```

### PR DESCRIPTION
**Pull request by mati865**
Fixes #836

### CODE REVIEW

File: wild/tests/integration_tests.rs [hunk 1]
```diff
@@ -1574,10 +1574,11 @@ impl LinkCommand {
 
                     if direct_config.is_static {
                         command.arg("-static");
-                    } else {
-                        command
-                            .arg("-dynamic-linker")
-                            .arg(dynamic_linker_path(cross_arch));
+                    // TODO: `export-dynamic` test reproduces the problem only when using neither `-static` nor `-dynamic-linker`
```
Comment (davidlattimore) [inline wild/tests/integration_tests.rs]: I guess one option here would be to replace `is_static` with an enum. e.g. `//#Mode:static`, `//#Mode:dynamic`, `//#Mode:unspecified`. The current default would be `static`, but I'm also open to changing that default to `unspecified` if we wanted - although we'd need to update a bunch of tests to explicitly specify `//#Mode:static`.
