### PR TITLE
linker-diff: Detect differences between program segments

### LINKED ISSUE #721: Diff program segments in linker-diff
I noticed that Wild sets the alignment on the `GNU_STACK` segment to 1, whereas GNU ld sets it to 0x10. We should fix this, but ideally we should fix it in conjunction with making linker-diff detect this difference.

Not everything about program segments can be diffed, since things like file offsets, sizes etc are expected to be different. However, the flags (write, execute etc) should be the same as should the alignment.

I'd suggest perhaps using `version_diff.rs` as a guide for how this might be written - mostly because it's pretty short. The idea is that you write a function that takes a `&crate::Binary` as an argument and returns `Result<FieldValues>`. The field values can be of the form `{segment_type}.{property}` e.g. `GNU_STACK.alignment`. For the `LOAD` segments, you can either ignore them or include their flags as part of their key rather than as a value. e.g. `LOAD.RX.alignment` for the alignment of the executable `LOAD` segment.

Once this is implemented, you should find tests failing due to the incorrect alignment of GNU_STACK. The failure should look something like this:

```
segment.GNU_STACK.alignment
  wild 0x1
  ld 0x10
```

I'd probably suggest adding `segment.GNU_STACK.alignment` to the default ignore rules in `linker-diff/src/lib.rs`, then in a subsequent PR, removing it and fixing the alignment.

### PR DESCRIPTION
**Pull request by lapla-cogito**
close #721 

Modify linker-diff to detect differences in program segments. Also, update libwild to set `GNU_STACK.alignment` to `0x10`, consistent with GNU ld.

### CODE REVIEW

**Comment by lapla-cogito** [comment]
I'm marking this PR as a draft because I'm still unsure about how to handle `LOAD` segments. Currently, `LOAD` segments are excluded in `linker-diff/src/lib.rs`, but if I comment out that exclusion, a large number of differences like the following are reported:
```
segment.LOAD.R.alignment
  wild 0x1000
  ld 0x1000,0x1000
```
I don't believe these differences should be reported in the first place, so I'll look into whether they can be suppressed.

File: linker-diff/src/segment.rs [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    let e = LittleEndian;
+    let mut values = FieldValues::default();
+
+    for segment in object.elf_file.elf_program_headers() {
+        let p_type = segment.p_type(e);
+        let p_flags = segment.p_flags(e);
+        let p_align = segment.p_align(e);
+
+        match p_type {
+            PT_GNU_STACK => {
```
Comment (davidlattimore) [inline linker-diff/src/segment.rs]: It'd be good to do this for all segments except PT_LOAD. I'd suggest having a function that can convert the segment type to a string. e.g. see x86_64_rel_type_to_string for how this might be done.

File: linker-diff/src/lib.rs [hunk 2]
```diff
@@ -234,6 +235,8 @@ impl Config {
                 // If we don't optimise a TLS access, then we'll have references to __tls_get_addr,
                 // when GNU ld doesn't.
                 "dynsym.__tls_get_addr.*",
+                // temporary
```
Comment (davidlattimore) [inline linker-diff/src/lib.rs]: I think it's reasonable to ignore these differences. If you wanted to ignore less, you could perhaps just ignore `segment.load.R.*`, since I think that's the main one where GNU ld emits two segments and we only emit one.

**Review by davidlattimore — COMMENTED** [review]
Thanks for working on this!

File: linker-diff/src/lib.rs (hunk 2 above)
Comment (lapla-cogito) [reply linker-diff/src/lib.rs]: Thanks! I’ve adjusted it to specifically ignore only `segment.LOAD.R.*`.

File: linker-diff/src/segment.rs (hunk 1 above)
Comment (lapla-cogito) [reply linker-diff/src/segment.rs]: Thanks! I implemented `segment_type_to_string`. As a result, many differences are now being detected, so I'll take a closer look to decide which ones should be ignored and which ones should be addressed.

Comment (lapla-cogito) [reply linker-diff/src/segment.rs]: Looking at the [CI results](https://github.com/davidlattimore/wild/actions/runs/14826999703/job/41621556206), I feel that `segment.PT_GNU_PROPERTY.*` should be fixed, while the others (`segment.PT_NOTE.*`, `segment.PT_INTERP.*`, `segment.PT_PHDR.*`, `segment.PT_GNU_STACK.*`, and `segment.PT_GNU_RELRO.*`) can reasonably be ignored. Does that approach make sense?

File: linker-utils/src/elf.rs [hunk 3]
```diff
@@ -209,6 +209,29 @@ pub fn aarch64_rel_type_to_string(r_type: u32) -> Cow<'static, str> {
...
+        PT_PHDR,
+        PT_TLS,
+        PT_GNU_EH_FRAME,
+        PT_GNU_STACK,
+        PT_GNU_RELRO,
+        PT_GNU_PROPERTY
+    ] {
+        Cow::Borrowed(name)
+    } else {
+        unreachable!()
```
Comment (davidlattimore) [inline linker-utils/src/elf.rs]: This could be reached if one of the linkers emitted a segment type that we don't know about. I'd suggest changing this to return some string that contains the numeric value. e.g.  `Cow::Owned(format!("UNKNOWN_P_TYPE_{r_type}"))`

File: linker-diff/src/segment.rs (hunk 1 above)
Comment (davidlattimore) [reply linker-diff/src/segment.rs]: It's fine by me to ignore all of them, then we can fix whichever ones we think should be fixed in subsequent commits. It's also fine to fix one or two in this PR, provided the fixes are trivial and leave the rest as ignored. As to which ones should eventually be fixed and which ones aren't worth ever trying to make the same, it's hard to say without looking at why each one is different. That's probably easier to do once this change is merged.

File: linker-utils/src/elf.rs (hunk 3 above)
Comment (lapla-cogito) [reply linker-utils/src/elf.rs]: Thanks! Fixed.

File: linker-diff/src/segment.rs (hunk 1 above)
Comment (lapla-cogito) [reply linker-diff/src/segment.rs]: Alright. For now, I’ve made it so that all the items mentioned above are ignored. If anything seems in need of fixing later, I (or someone else) will address it separately.
